production:
#  address: 127.0.0.1
#  port: 9313
  min_infix_len: 2
  morphology: stem_enru, Soundex, Metaphone
  utf8: true
  enable_star: true
  use_star: true
  sql_query_pre:
      - "SET NAMES utf8"
  charset_table: "0..9, A..Z->a..z, _, a..z, U+410..U+42F->U+430..U+44F, U+430..U+44F"

development:
  min_infix_len: 2
